version: "3.3"
services:
 ctfopensource:
  build: .
  environment:
    - TIME_ZONE=Europe/Paris
  #volumes:
   #- ./run/var/storage:/var/www/html/storage #TODO : probleme chmod ici
   #- ./.env:/var/www/html/.env
   #- ./database/database.sqlite:/var/www/html/database/database.sqlite
  ports:
   - "8080:80"
